from .compute_real_estate_pressure import compute_real_estate_pressure
from .calculate_nb_equipements import calculate_nb_equipements
from .density_of_services import density_of_services
from .normalize_real_estate_pressure import normalize_real_estate_pressure
from .quality_of_life import quality_of_life